version: '4'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - app-network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true

  rabbit:
    image: rabbitmq:management-alpine
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq

networks:
  app-network:
    driver: bridge

volumes:
  rabbit_data:
  caddy_data:
  caddy_config:
