version: '4'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/php:1-8.2-bullseye
    restart: unless-stopped
    command: tail -f /dev/null
    networks:
      - app-network
    ports:
      - 8000:8000
    volumes:
      - ../..:/workspaces:cached

  rabbit:
    image: rabbitmq:management-alpine
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq

networks:
  app-network:
    driver: bridge

volumes:
  rabbit_data:
  caddy_data:
  caddy_config:
